config/routes.rb
Rails.application.routes.draw do
  devise_for :users , controllers:{
    confirmations:'confirmations',
    registrations:'registrations',
  } do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end



  get '/pop' => 'posts#new' , as:"new_post"
  post '/pop' => 'posts#create'
  get '/feed' => 'users#feed'
  put '/posts/:id/like' => 'posts#like' , as: 'like'
  post '/posts/:id/comment' => 'posts#comment' , as:'comment'
  get '/users/:id' => 'users#show' , as:"profile"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'users#feed'
  get '/m' => 'messages#index'
  resources :posts , only:[:show]
  resources :messages , only:[:create , :new]
  #ahas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user , dependent: :destroy
  belongs_to :post , dependent: :destroy
  validates :user_id, uniqueness:{scope: :post_id}
end

app/models/message.rb
class Message < ApplicationRecord
   belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :likes , dependent: :destroy
    has_many :comments, -> { order(created_at: :desc) }, dependent: :destroy
    def liked?(user)
        !!self.likes.find{|like| like.user_id == user.id}
    end
    validates :post , length:{minimum:20}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts ,  dependent: :destroy
  has_many :messages , dependent: :destroy
  has_many :likes
  has_many :comments
  zodiac_reader :birthday

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable , :confirmable
  validates :email , format:{with:/\A.+@nitk.edu.in+\z/ , message:"NITK edu account required"}
  validates :username , length: { minimum: 5 , maximum:15 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # protect_from_forgery with: :exception
    # skip_before_action :verify_authenticity_token

    before_action :set_user

    private

    def user_signed_in?
      current_user
    end

    def set_user
      if user_signed_in?
        cookies.signed[:current_user] = current_user.id
      else
        cookies.delete(:current_user)
      end
     end

    
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
    private
    def after_confirmation_path_for(resource_name , resource)
        sign_in(resource)
        feed_path
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def new 
        @message = Message.new
    end

    def index
        @message = Message.new
        @messages = Message.all
    end
    def create
         
            @message = Message.create(user_id:current_user.id , message:message_params[:message])

            if @message.save
                ActionCable.server.broadcast 'room_channel' , {content:params[:message] , user_id: current_user.id , username:current_user.username}
            else
                redirect_to root_path
            end
            
    end

    private
    def message_params
        params.permit(:message, :authenticity_token, :commit)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    skip_before_action :verify_authenticity_token

    def new 
        @post = Post.new
    end
    
    def show
        @post = Post.find(params[:id])
    end
    
    def create
        @p = Post.new(post:params[:post] , user_id:current_user.id)
        if @p.save 
            redirect_to root_path
        else
            render root_path
        end
        
    end

    def like
        @post = Post.all.find(params[:id])
        Like.create(user_id:current_user.id , post_id:@post.id)
        redirect_to root_path
    end

    def comment
        
        @comment = Comment.new(comment:params[:comment] , post_id:params[:id] , user_id:current_user.id)
        if @comment.save 
            redirect_to "/posts/#{params[:id]}"
        else
            redirect_to
        end
    end

   
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
  
    def sign_up_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation , :birthday)
    end
  
    def account_update_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password , :birthday)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    def index
        @user = current_user   
    end

    def feed
        @post = Post.all
    end

    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_comment.html.erb
  <%= form_with(model:@comment , url: comment_path(obj), method: "create") do |f| %>
<!--  <div class="row">-->

  
<!--    <div class="col-8">-->
      <%#= f.text_field :comment , class:"comment-box" , autocomplete:"off" , placeholder:"Enter a comment"%>

<!--    </div>-->
<!--    <div class="col-4 d-flex justify-content-end">-->
<!--      <p class="date">-->

        <%#= f.submit "comment" , class:"comment-button" %>

<!--      </p>-->

<!--    </div>-->
    
<!--    </div>-->
<div class="container w-1/2 mx-auto flex flex-row justify-between mb-8">
  <%= f.text_field :comment , class:"rounded-sm p-4 shadow-md w-full mr-10" , autocomplete:"off" , placeholder:"Enter a comment"%>

  <%= f.submit "comment" , class:"text-secondary px-2" %>

</div>

  <% end %>

app/views/layouts/_commentSection.html.erb
<% comments.each do |c| %>

  
<!--<div class="row">-->
<!--<div class="col-md-1 col-sm-2 comment-username">-->
<!--<a href="<%#=profile_path(c.user)%>"><%#=c.user.username%></a>-->
<!--</div>-->

<!--  <div class="col-md-10 col-sm-9 comment-comment">-->

  <%#=c.comment%>
<!--  </div>-->
<!--  <div class="col-md-1 col-sm-1">-->
    <%#=c.created_at.strftime("%d %b")%>
<!--  </div>-->
<!--</div> -->

<div class="mb-8">
  <div class="flex flex-row items-center pb-3">
  <img class="w-10 rounded-full" src="https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8cGVyc29ufGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&w=1000&q=80">
  </img>
    <div>

  <p class="text-sm px-4">
    <%=c.user.username.capitalize%>
  </p>

      <p class="text-xs px-4 text-gray-500">
        <%=c.created_at.strftime("%d %b")%>
      </p>
    </div>
    </img>
  </div>
  <div>
    <p class="font-light text-sm text-gray-700"><%=c.comment%></p>
  </div>

</div>

<%end%>

app/views/layouts/_navigation.html.erb
<!-- new navigation -->
<!--<nav class="navigation">-->
<!--  <div class="container mx-auto p-5">-->
<!--    <div class="row align-items-center">-->
<!--      <div class="col-4">-->
      <%#= link_to '<span class="material-icons">face</span>'.html_safe, profile_path(current_user) , class:"" %>
<!--      </div>-->
<!--      <div class="col-4 d-flex justify-content-center"><a class="nav-link" href="/feed"><img src="<%#=asset_path('logo.png')%>"><span class="nav-title">Popcorn</span></a>-->
<!--      </div>-->


<!--      <div class="col-4 d-flex justify-content-end">-->
        
       <%#= link_to '<span class="material-icons">bookmark</span>'.html_safe, m_path , :data => { :no_turbolink => true } %>
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<!--</nav>-->

<div class="flex shadow-lg justify-between flex-row items-center w-full h-16 bg-primary">
  <div class="pl-12">
    <%= link_to profile_path(current_user)  do%>
      <span class="material-icons text-secondary">face</span>
    <%end %>
  </div>
  <div class="flex flex-row items-center">
    <%= link_to "/feed"  do%>
      <img class="h-7 inline" src="<%=asset_path('logo.png')%>">
    <%end %>
    <p class="text-secondary hidden md:inline pl-5 font-extrabold">POP-CHAN</p>

  </div>
  <div class="pr-12">
    <div>
      <%= link_to m_path , :data => { :no_turbolink => true } do%>
        <span class="material-icons text-secondary">bookmark</span>
      <%end%>

    </div>
  </div>
</div>

app/views/layouts/_news.html.erb
<!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">

  <!--Indicators-->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-1z" data-slide-to="1"></li>
    <li data-target="#carousel-example-1z" data-slide-to="2"></li>
   

  </ol>
  <!--/.Indicators-->

  <!--Slides-->
  <div class="carousel-inner" role="listbox">

    <!--First slide-->
    <div class="carousel-item active">
      <div class="view welcome"">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

          <!-- Content -->
          
          <!-- Content -->

        </div>
        <!-- Mask & flexbox options-->

      </div>
    </div>
    <!--/First slide-->
    <%=render 'layouts/newsholder'%>
    <%=render 'layouts/newsholder'%>
    

  

  </div>
  <!--/.Slides-->

  <!--Controls-->
  <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <!--/.Controls-->

</div>
<!--/.Carousel Wrapper-->

app/views/layouts/_newsholder.html.erb
<!--Second slide-->
    <div class="carousel-item">
      <div class="view" >

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

          <!-- Content -->
          
          <!-- Content -->

        </div>
        <!-- Mask & flexbox options-->

      </div>
    </div>
    <!--/Second slide-->

app/views/layouts/_nocomments.html.erb
<h3 style="text-align:center;">
    No comments XD , lol 
</h3>

app/views/layouts/_pop.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary floating" data-toggle="modal" data-target="#exampleModalCenter">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%=render "form" %>
      </div>
  
    </div>
  </div>
</div>

app/views/layouts/_post.html.erb
<!--<div class="container postholder">-->
<!--  <div class="row">-->
<!--     <div class="col-9">-->
<!--       <p class="username" ><img class="rounded-circle profile-logo" src="https://w7.pngwing.com/pngs/88/959/png-transparent-scorpio-taurus-astrological-sign-astrology-aries-taurus-text-logo-computer-wallpaper.png"> <a href="<%#=profile_path(obj.user)%>"><%#=obj.user.username.capitalize%></a></p></div>-->
<!--     <div class="col-3"><p class="date"><%#=obj.created_at.strftime("%d %b")%></p></div>-->
<!--  </div>-->
<!--  <div class="row">-->
<!--    <div class="col-12"><p class="pop"> <img class="quote" src="<%#=asset_path('quote.svg')%>"><%#=obj.post%> </p> </div>-->
    
<!-- </div>-->
<!-- <div class="row">-->
<!--  <div class="col-8 response">-->
    <%#if obj.liked?(current_user)%>
    
<!--    <i class="bi bi-heart-fill">Hearted</i>-->
    <%#else%>
    
    <%#= link_to '<i class="bi bi-heart">Heart</i>'.html_safe , like_path(obj) , remote:true, method: :put  %>
    
    <%#end%>
   
    <%#= link_to '<i class="bi bi-chat-square-dots">Comment</i>'.html_safe , post_path(obj) %>
    
<!--    <a href="whatsapp://send?text=<%#=obj.post%>"       data-action="share/whatsapp/share"  -->
<!--        target="_blank"> <i class="bi bi-arrow-90deg-right">Share</i> </a>-->
<!--  </div>-->
<!--  <div class="col-4 d-flex justify-content-end like-count"><p><%#=pluralize(obj.likes.count , "Heart")%> </p></div> -->
<!--</div>-->

<div class="bg-white w-full rounded p-5">
  <div class="w-full pb-8 flex flex-row justify-between items-center">
    <a class="block" href="<%=profile_path(obj.user)%>">

  <div class="flex-row flex items-center">
    <img class="rounded-full w-10 border-4 border-blue-500" src="https://w7.pngwing.com/pngs/88/959/png-transparent-scorpio-taurus-astrological-sign-astrology-aries-taurus-text-logo-computer-wallpaper.png">
    <h6 class="font-medium pl-4 text-xl text-primary hover:underline"><%=obj.user.username.capitalize%></h6>
  </div>
    </a>

    <p class="text-primary text-sm">
      <%=obj.created_at.strftime("%d %b")%>
    </p>
  </div>

  <div class="flex-row flex justify-between items-start pb-8">
    <p class="text-gray-800 font-extralight text-3xl leading-relaxed pr-1">
      <%=obj.post.capitalize%> ~
    </p>
    <img class="w-48px top-0 right-0 opacity-20" alt="quote image" src="<%=asset_path('quote.svg')%>"/>
  </div>

  <div class="">
      <span class="material-icons text-gray-700 opacity-90 hover:opacity-100 cursor-pointer">favorite</span>

    <%= link_to post_path(obj) do%>
      <span class="material-icons text-gray-700  pl-2 opacity-90 hover:opacity-100 cursor-pointer">comment</span>

      <%end%>
    <span class="material-icons text-gray-700  pl-2 opacity-90 hover:opacity-100 cursor-pointer">share</span>

  </div>

</div>

</div>

app/views/layouts/_postholder.html.erb
<% obj.reverse.each do |o|%>
<div class="container w-1/2 mx-auto mb-5  mt-5 shadow-md hover:shadow-lg transition-all duration-300 cursor-pointer">
<%=render "layouts/post" , obj:o%>
</div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Popcorn</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= csrf_meta_tags %>
    
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>


    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= notice %>
    <%=alert%>
  </head>
<header>
</header>  
<body class="bg-gray-100">
<%=render("layouts/navigation") if user_signed_in? %>
   <div >
     <%= yield %>
   </div>
  </body>
</html>

app/views/messages/index.html.erb
<!-- <div class="inner">Hello</div> -->
<div class="pb-12">




<div class="container mx-auto pb-12 chat-box overflow-auto" data-user-id=<%=current_user.id%>>

        <%@messages.each do |message|%>
        
          <% if message.user_id == current_user.id%>
             <div class="flex flex-row justify-end ">
               <p class="message-text text-sm font-light inline bg-blue-300  p-3 mt-2 mb-2 rounded-t-full rounded-bl-full">
                 <%= message.message%>
               </p>
             </div>
          <%else%>

      <div class="flex flex-row justify-start ">
        <p class="message-text text-sm font-light  inline bg-green-300  p-3 mt-2 mb-2 rounded-t-full rounded-br-full">
          <%= message.message%>
        </p>
      </div>
          <%end%>
        <%end%>
 
   
</div>
  <%= form_with url:messages_path , method:"post" ,local: false , class:"chat-form fixed bottom-0 w-full bg-yellow-300" do |f|%>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <div class="flex flex-row justify-between items-center">


      

        <%=f.text_field :message  , class:"message-box w-full bg-transparent pl-8 placeholder-yellow-900 p-5" , autocomplete:"off", placeholder:"Enter message here"%>


  <%= f.submit "Send", class:"message-button bg-transparent pr-8"%>

    </div>

<%end%>
</div>

app/views/messages/new.html.erb
<div class="inner">Hello</div>

<%= form_with model:@message  , remote: true do |f|%>
<%=f.text_field :message %>
<%= f.submit %>

<%end%>

app/views/posts/new.html.erb
<div class="container mx-auto w-1/2 pt-10">


    <%= form_with(model:@posts) do |f| %>

    
  

    <textarea name="post" rows="5"  spellcheck="false" placeholder="What's in your mind?"
              class="p-5 shadow-md text-secondary text-3xl rounded-t-3xl rounded-bl-3xl bg-white w-full"></textarea>

  
        

    <div class="flex justify-end">
        <%= f.submit "Post" ,class:"px-10 pt-3 pb-3 rounded-full bg-indigo-700 shadow-md text-white ml-auto"%>
    </div>
    <% end %>


  </div>

app/views/posts/show.html.erb
<div class="container w-1/2 mx-auto mb-5  mt-5 shadow-md hover:shadow-lg transition-all duration-300 cursor-pointer">
  <%=render "layouts/post" , obj:@post%>
</div>

<div class="row justify-content-center">
<%=render "layouts/comment" , obj:@post%>
</div>

<div class="container container w-1/2 mx-auto pb-2" >

    <%if @post.comments.count != 0 %>

<%= render "layouts/commentSection" , comments: @post.comments.includes(:user) %>
<%else%>
<%= render "layouts/nocomments" , obj:@post%>
<%end%>

</div>

app/views/users/_form.html.erb
<%= form_with(model:@post , url: pop_path(@post), method: "create" , remote:true) do |f| %>
    <h1 class="display-1">Pop</h1>
    
    <div class="field">
    <%= f.label :title %><br/>
    <%= f.text_field :title%>
  </div>  
  <div class="field">
    <%= f.label :post %><br/>
    <%= f.text_field :post%>
  </div>
  
    <div class="actions">
      <%= f.submit "pop" %>
    </div>
<% end %>

app/views/users/feed.html.erb
<%=render 'layouts/postholder' , obj:@post %>

app/views/users/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <div class="row">
     <div class="col-8">
      <h1>This is Scary</h1> 
     </div>
    </div>
  </div>
</div>


<%= render "layouts/postholder" , obj:@user.posts%>

app/views/users/show.html.erb
<div class="container w-1/2 mx-auto bg-yellow-300 px-4 pt-8 pb-8 rounded-md shadow-md mt-8 mb-12 relative">
  <div class="person-info w-full flex-row flex items-center">
    <img class="w-20" src="<%=asset_path('logo.png')%>">
    <div class="pl-10">
      <h2 class="text-3xl font-bold mb-2"><%=@user.username.capitalize%></h2>
      <p class="text-sm text-gray-700">Keen interest in 📚 <br/>Regular reader of Poppy 🍭</p>
    </div>
    <div class="ml-auto flex flex-col items-center">
      <%=link_to edit_user_registration_path do%>
        <button class="p-1.5 text-sm rounded-sm border-1 border-gray-700 mb-2">
          Edit profile
        </button>
      <%end%>

      <%=link_to destroy_user_session_path, method: :delete do%>
        <button class="p-1.5 text-sm rounded-sm text-red-600">
          Log out
        </button>
      <%end%>
    </div>
  </div>


  <%=link_to new_post_path,class:"bg-black rounded-full w-48px h-48px flex items-center absolute bottom-0 -mb-5 right-1/4 transform translate-x-3/4" do%>
    <span class="mx-auto material-icons text-secondary">add</span>
  <%end %>
</div>

<!-- NUMBER OF POSTS CREATED-->
<!--BRANCH FROM-->



<%= render "layouts/postholder" , obj:@user.posts%>